global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhook_receiver' # Default receiver

receivers:
  - name: 'webhook_receiver'
    webhook_configs:
      - url: 'http://your-webhook-url.com/alert' # REPLACE THIS WITH YOUR ACTUAL WEBHOOK URL
        send_resolved: true
  # Example for email receiver (uncomment and configure if needed)
  # - name: 'email_receiver'
  #   email_configs:
  #     - to: 'your-email@example.com'
  #       from: 'alertmanager@example.com'
  #       smarthost: 'smtp.example.com:587'
  #       auth_username: 'smtp_user'
  #       auth_password: 'smtp_password'
  #       require_tls: true
