groups:
  - name: node_exporter_alerts
    rules:
      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is at {{ $value | printf \"%.2f\" }}% for more than 5 minutes on instance {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: 100 * (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Memory usage on {{ $labels.instance }}"
          description: "Memory usage is at {{ $value | printf \"%.2f\" }}% for more than 5 minutes on instance {{ $labels.instance }}."

  - name: blackbox_exporter_alerts
    rules:
      - alert: ServiceDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "Service {{ $labels.instance }} is unreachable or returning non-2xx status codes."
