global:
  scrape_interval: 15s # How frequently to scrape targets

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module from blackbox.yml
    static_configs:
      - targets:
          - http://grafana:3000 # Example: Monitor Grafana's availability
          - http://prometheus:9090 # Example: Monitor Prometheus's availability
          - http://localhost:80 # Example: Monitor an external website (replace with your target)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Blackbox exporter's address

  - job_name: 'pushgateway'
    honor_labels: true # Important for Pushgateway to preserve labels
    static_configs:
      - targets: ['pushgateway:9091']
